<?php

/**
 * @file
 * Tide News module.
 */

use Drupal\workflows\Entity\Workflow;

/**
 * Implements hook_entity_bundle_create().
 */
function tide_news_entity_bundle_create($entity_type_id, $bundle) {
  // Enable News in Editorial workflow if workflow module is enabled.
  if ($entity_type_id == 'node' && $bundle == 'news') {
    /** @var \Drupal\Core\Extension\ModuleHandlerInterface $moduleHandler */
    $moduleHandler = \Drupal::service('module_handler');
    if ($moduleHandler->moduleExists('workflows')) {
      $editorial_workflow = Workflow::load('editorial');
      if ($editorial_workflow) {
        $editorial_workflow->getTypePlugin()
          ->addEntityTypeAndBundle('node', 'news');
        $editorial_workflow->save();
      }
    }
  }
}

function tide_news_search_api_index_items_alter(\Drupal\search_api\IndexInterface $index, array &$items) {
  foreach ($items as $item_id => $item) {

    $content_type = $item->getField('type');
    if (empty($content_type) || $content_type->getValues()[0] !== 'news') {
      continue;
    }

    // Format date of a field_news_date
    $date = $item->getField('field_news_date');
    if (!empty($date)) {
      $values = $date->getValues();
      $date_value = !empty($values) ? _tide_news_get_formatted_date($values[0]) : NULL;
      $date->setValues([$date_value]);
      $item->setField("field_news_date", $date);
    }
  }
}


/**
 * Converts timestamp to RFC-3339 format.
 *
 * TODO: Refactor this as a helper in tide_core/includes/helpers.inc SDPA-1071.
 *
 * @param int $ts
 *   Timestamp.
 * @return string
 *   Formatted date.
 */
function _tide_news_get_formatted_date($ts) {
  $config = \Drupal::config('system.date');
  $timezone = new DateTimeZone($config->get('timezone.default'));
  $date = new \Datetime();
  $date->setTimezone($timezone);
  $date = $date->setTimestamp($ts);
  return $date->format("Y-m-d\TH:i:sP");
}
